import React from 'react';
import {Link, Switch} from "react-router-dom";
import Header from "../../Components/Layouts/AuthLayout/Header";
import MainFooter from "./../../Components/Layouts/MainFooter";

import '../../assets/css/style.css';
class termOfUse extends React.Component {
    state = {
       
       
    }
   

    render() {
        return (
            <div>
            <Header />
          <section className="legal-page">
  <div className="container">
    <div className="row">
      <div className="col-md-12">
        <div className="legal-page-width">
          <div className="legal-page-heading">
          <span className="legaldate">Last revised on 27 Jun 2022</span>
          <h1>Terms of Use</h1>
          </div>
          <div className="legal-page-desc">
          <p>Welcome to the Terms of Service (these “Terms”) for the website, www.candoor.io (the “Website”), operated on behalf of Candoor, Inc. (“Company”, “we” or “us”), and together with any content, tools, features and functionality offered on or through our Website (the “Services”).</p>
          <p>These Terms govern your access to and use of the Services.  Please read these Terms carefully, as they include important information about your legal rights. By accessing and/or using the Services, you are agreeing to these Terms. If you do not understand or agree to these Terms, please do not use the Services.</p>
           <p>For purposes of these Terms, “you” and “your” means you as the user of the Services. If you use the Services on behalf of a company or other entity then “you” includes you and that entity, and you represent and warrant that (a) you are an authorized representative of the entity with the authority to bind the entity to these Terms, and (b) you agree to these Terms on the entity's behalf. </p>
           <h2>1. Who May Use the Services</h2>
           <p>You must be 13 years of age or older and reside in the United States or any of its territories to use the Services. Minors under the age of majority in their jurisdiction but that are at least 13 years of age are only permitted to use the Services if the minor’s parent or guardian accepts these Terms on the minor’s behalf prior to use of the Services. Children under the age of 13 are not permitted to use the Services. By using the Services, you represent and warrant that you meet these requirements.</p>
           <h2>2. User Accounts</h2>
           <p><a href="#">Creating and Safeguarding your Account.</a> To use the Services, you may need to create an account (“Account”). You agree to provide us with accurate, complete and updated information for your Account. You can access, edit and update your Account by visiting your Settings, which can be accessed via the header navigation bar in the dropdown menu under your avatar photo.</p> 
           <p>You are solely responsible for any activity on your Account and for maintaining the confidentiality and security of your password. We are not liable for any acts or omissions by you in connection with your Account. You must immediately notify us at helo@candoor.io if you know or have any reason to suspect that your Account or password have been stolen, misappropriated or otherwise compromised, or in case of any actual or suspected unauthorized use of your Account. </p>
           <h2>3. Location of Privacy Policy</h2>
           <p><a href="#">Privacy Pollicy.</a> Our Privacy Policy describes how we handle the information you provide to us when you use the Services. For an explanation of our privacy practices, please visit our Privacy Policy located at www.candoor.io/privacy_policy.</p>
           <h2>4. Rights We Grant You</h2>
           <p><a href="#">License Grant.</a> Subject to your compliance with these Terms, the Company hereby grants to you, a personal, worldwide, royalty-free, non-assignable, non-sublicensable, non-transferrable, and non-exclusive license to use the software provided to you as part of the Services. This license has the sole purpose of enabling you to use and enjoy the benefit of the Services as provided by us, in the manner permitted by these Terms and subject to the use restrictions described below. Your access and use of the Services may be interrupted from time to time for any of several reasons, including, without limitation, the malfunction of equipment, periodic updating, maintenance or repair of the Service or other actions that Company, in its sole discretion, may elect to take.</p>
           <h3>4.1 License Grant</h3>
           <p>Subject to your compliance with these Terms, the Company hereby grants to you, a personal, worldwide, royalty-free, non-assignable, non-sublicensable, non-transferrable, and non-exclusive license to use the software provided to you as part of the Services. This license has the sole purpose of enabling you to use and enjoy the benefit of the Services as provided by us, in the manner permitted by these Terms and subject to the use restrictions described below. Your access and use of the Services may be interrupted from time to time for any of several reasons, including, without limitation, the malfunction of equipment, periodic updating, maintenance or repair of the Service or other actions that Company, in its sole discretion, may elect to take.</p>
           <h3>4.2 Restrictions On Your Use of the Services.</h3>
           <p>You may not do any of the following, unless applicable laws or regulations prohibit these restrictions or you have our written permission to do so:</p>
           <ul>
             <li>Download, modify, copy, distribute, transmit, display, perform, reproduce, duplicate, publish, license, create derivative works from, or offer for sale any information contained on, or obtained from or through, the Services;</li>
             <li>Duplicate, decompile, reverse engineer, disassemble or decode the Services (including any underlying idea or algorithm), or attempt to do any of the same;</li>
             <li>Use, reproduce or remove any copyright, trademark, service mark, trade name, slogan, logo, image, or other proprietary notation displayed on or through the Services;</li>
             <li>Use automation software (bots), hacks, modifications (mods) or any other unauthorized third-party software designed to modify the Services;</li>
             <li>Exploit the Services for any commercial purpose, including without limitation communicating or facilitating any commercial advertisement or solicitation;</li>
             <li>Access or use the Services in any manner that could disable, overburden, damage, disrupt or impair the Services or interfere with any other party's access to or use of the Services or use any device, software or routine that causes the same;</li>
             <li>Attempt to gain unauthorized access to, interfere with, damage or disrupt the Services, accounts registered to other users, or the computer systems or networks connected to the Services;</li>
             <li>Circumvent, remove, alter, deactivate, degrade or thwart any technological measure or content protections of the Services;</li>
             <li>Use any robot, spider, crawlers or other automatic device, process, software or queries that intercepts, “mines,” scrapes or otherwise accesses the Services to monitor, extract, copy or collect information or data from or through the Services, or engage in any manual process to do the same;</li>
             <li>Introduce any viruses, trojan horses, worms, logic bombs or other materials that are malicious or technologically harmful into our systems;</li>
             <li>Use the Services for illegal, harassing, unethical, or disruptive purposes;</li>
             <li>Violate any applicable law or regulation in connection with your access to or use of the Services; or</li>
             <li>Access or use the Services in any way not expressly permitted by these Terms.</li>
           </ul>
           <h2>5. Ownership & Content</h2>
           <h3>5.1 Ownership of the Services</h3>
           <p>The Services, including their "look and feel" (e.g., text, graphics, images, logos), proprietary content, information and other materials, are protected under copyright, trademark and other intellectual property laws. You agree that the Company and/or its licensors own all right, title and interest in and to the Services (including any and all intellectual property rights therein) and you agree not to take any action(s) inconsistent with such ownership interests.  We and our licensors reserve all rights in connection with the Services and its content (other than Your Content), including, without limitation, the exclusive right to create derivative works. </p>
           <h3>5.2 Ownership of Trademarks</h3>
           <p>The Company’s name, CANDOOR, the Company’s logo and all related names, logos, product and service names, designs and slogans are trademarks of the Company or its affiliates or licensors.  Other names, logos, product and service names, designs and slogans that appear on the Services are the property of their respective owners, who may or may not be affiliated with, connected to, or sponsored by us.  </p>
           <h3>5.3 Ownership of Feedback</h3>
           <p>We welcome feedback, comments and suggestions for improvements to the Services (“Feedback”). You acknowledge and expressly agree that any contribution of Feedback does not and will not give or grant you any right, title or interest in the Services or in any such Feedback. All Feedback becomes the sole and exclusive property of the Company, and the Company may use and disclose Feedback in any manner and for any purpose whatsoever without further notice or compensation to you and without retention by you of any proprietary or other right or claim. You hereby assign to the Company any and all right, title and interest (including, but not limited to, any patent, copyright, trade secret, trademark, show-how, know-how, moral rights and any and all other intellectual property right) that you may have in and to any and all Feedback. </p>
           <h3>5.4 Your Content License Grant</h3>
           <p>In connection with your use of the Services, you may be able to post, upload, or submit content to be made available through the Services (“Your Content”).  In order to operate the Service, we must obtain from you certain license rights in Your Content so that actions we take in operating the Service are not considered legal violations.  Accordingly, by using the Service and uploading Your Content, you grant us a license to access, use, host, cache, store, reproduce, transmit, display, publish, distribute, and modify (for technical purposes, e.g., making sure content is viewable on smartphones as well as computers and other devices) Your Content but solely as required to be able to operate and provide the Services.  You agree that these rights and licenses are royalty free, transferable, sub-licensable, worldwide and irrevocable (for so long as Your Content is stored with us), and include a right for us to make Your Content available to, and pass these rights along to, others with whom we have contractual relationships related to the provision of the Services, solely for the purpose of providing such Services, and to otherwise permit access to or disclose Your Content to third parties if we determine such access is necessary to comply with our legal obligations.  As part of the foregoing license grant you agree that the other users of the Services shall have the right to comment on and/or tag Your Content and/or to use, publish, display, modify or include a copy of Your Content as part of their own use of the Services; except that the foregoing shall not apply to any of Your Content that you post privately for non-public display on the Services. By posting or submitting Your Content through the Services, you represent and warrant that you have, or have obtained, all rights, licenses, consents, permissions, power and/or authority necessary to grant the rights granted herein for Your Content. You agree that Your Content will not contain material subject to copyright or other proprietary rights, unless you have the necessary permission or are otherwise legally entitled to post the material and to grant us the license described above.  </p>
           <h3>5.5 Notice of Infringement – DMCA Policy </h3>
           <p>If you believe that any text, graphics, photos, audio, videos or other materials or works uploaded, downloaded or appearing on the Services have been copied in a way that constitutes copyright infringement, you may submit a notification to our copyright agent in accordance with 17 USC 512(c) of the Digital Millennium Copyright Act (the “DMCA”), by providing the following information in writing:</p>
           <ul>
             <li>Identification of the copyrighted work that is claimed to be infringed;</li>
             <li>Identification of the allegedly infringing material that is requested to be removed, including a description of where it is located on the Service;</li>
             <li>Information for our copyright agent to contact you, such as an address, telephone number and e-mail address;</li>
             <li>A statement that you have a good faith belief that the identified, allegedly infringing use is not authorized by the copyright owners, its agent or the law;</li>
             <li>A statement that the information above is accurate, and under penalty of perjury, that you are the copyright owner or the authorized person to act on behalf of the copyright owner; and</li>
             <li>The physical or electronic signature of a person authorized to act on behalf of the owner of the copyright or of an exclusive right that is allegedly infringed.</li>
             <li>Notices of copyright infringement claims should be sent by e-mail to hello@candoor.io.  It is our policy, in appropriate circumstances and at our discretion, to disable or terminate the accounts of users who repeatedly infringe copyrights or intellectual property rights of others.</li>
           </ul>
            <p>A user of the Services who has uploaded or posted materials identified as infringing as described above may supply a counter-notification pursuant to sections 512(g)(2) and (3) of the DMCA. When we receive a counter-notification, we may reinstate the posts or material in question, in our sole discretion. To file a counter-notification with us, you must provide a written communication (by fax or regular mail or by email) that sets forth all of the items required by sections 512(g)(2) and (3) of the DMCA. Please note that you will be liable for damages if you materially misrepresent that content or an activity is not infringing the copyrights of others. </p>
            <h2>6. Third Party Services and Materials </h2>
            <h3>6.1 Use of Third Party Materials in the Services</h3>
            <p>Certain Services may display, include or make available content, data, information, applications or materials from third parties (“Third Party Materials”) or provide links to certain third party websites. By using the Services, you acknowledge and agree that the Company is not responsible for examining or evaluating the content, accuracy, completeness, availability, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of such Third Party Materials or websites. We do not warrant or endorse and do not assume and will not have any liability or responsibility to you or any other person for any third-party services, Third Party Materials or third-party websites, or for any other materials, products, or services of third parties. Third Party Materials and links to other websites are provided solely as a convenience to you.  </p>
            <h2>7. Disclaimers, Limitations of Liability and Indemnification</h2>
            <h3>7.1 Disclaimers</h3>
            <p>Your access to and use of the Services are at your own risk. You understand and agree that the Services are provided to you on an “AS IS” and “AS AVAILABLE” basis. Without limiting the foregoing, to the maximum extent permitted under applicable law, the Company, its parents, affiliates, related companies, officers, directors, employees, agents, representatives, partners and licensors (the “the Company Entities”) DISCLAIM ALL WARRANTIES AND CONDITIONS, WHETHER EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. The Company Entities make no warranty or representation and disclaim all responsibility and liability for: (a) the completeness, accuracy, availability, timeliness, security or reliability of the Services; (b) any harm to your computer system, loss of data, or other harm that results from your access to or use of the Services; (c) the operation or compatibility with any other application or any particular system or device; (d) whether the Services will meet your requirements or be available on an uninterrupted, secure or error-free basis; and (e) the deletion of, or the failure to store or transmit, Your Content and other communications maintained by the Services. No advice or information, whether oral or written, obtained from the Company Entities or through the Services, will create any warranty or representation not expressly made herein.</p>
            <h3>7.2 Limitations of Liability</h3>
            <p>TO THE EXTENT NOT PROHIBITED BY LAW, YOU AGREE THAT IN NO EVENT WILL THE COMPANY ENTITIES BE LIABLE (A) FOR DAMAGES OF ANY KIND, INCLUDING DIRECT, INDIRECT, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, LOSS OF USE, DATA OR PROFITS, BUSINESS INTERRUPTION OR ANY OTHER  DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OR INABILITY TO USE THE SERVICES), HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, WHETHER UNDER THESE TERMS OR OTHERWISE ARISING IN ANY WAY IN CONNECTION WITH THE SERVICES OR THESE TERMS AND WHETHER IN CONTRACT, STRICT LIABILITY OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) EVEN IF THE COMPANY ENTITIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE, OR (B) FOR ANY OTHER CLAIM, DEMAND OR DAMAGES WHATSOEVER RESULTING FROM OR ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR THE DELIVERY, USE OR PERFORMANCE OF THE SERVICES.  SOME JURISDICTIONS (SUCH AS THE STATE OF NEW JERSEY) DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE EXCLUSION OR LIMITATION MAY NOT APPLY TO YOU. THE COMPANY ENTITIES’ TOTAL LIABILITY TO YOU FOR ANY DAMAGES FINALLY AWARDED SHALL NOT EXCEED THE GREATER OF THE AMOUNT OF ONE HUNDRED DOLLARS ($100.00), OR THE AMOUNT YOU PAID THE COMPANY ENTITIES, IF ANY, IN THE PAST SIX (6) MONTHS FOR THE SERVICES (OR OFFERINGS PURCHASED ON THE SERVICES) GIVING RISE TO THE CLAIM. THE FOREGOING LIMITATIONS WILL APPLY EVEN IF THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE. </p>
            <h3>7.3 Indemnification</h3>
            <p>By entering into these Terms and accessing or using the Services, you agree that you shall defend, indemnify and hold the Company Entities harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys’ fees and costs) incurred by the Company Entities arising out of or in connection with: (a) your violation or breach of any term of these Terms or any applicable law or regulation; (b) your violation of any rights of any third party; (c) your access to or use of the Services; (d) Your Content, or (e) your negligence or wilful misconduct.</p>
            <h2>8. ARBITRATION AND CLASS ACTION WAIVER</h2>
            <h3>8.1 Informal Process First</h3>
            <p>You agree that, in the event of any dispute between you and the Company Entities, you will first contact the Company in writing and make a good faith sustained effort to resolve the dispute before resorting to more formal means of resolution, including without limitation, any arbitration or court action.</p>
            <h3>8.2 Arbitration Agreement and Class Action Waiver</h3>
            <p>If the dispute remains unresolved thirty (30) days after you first contact the Company in writing under Section 9.1, any remaining dispute, controversy, or claim (collectively, “Claim”) relating in any way to your purchase or use of the Offerings, will be resolved by arbitration, including threshold questions of arbitrability of the Claim. You and the Company agree that any Claim will be settled by final and binding arbitration, using the English language, administered by JAMS under its Comprehensive Arbitration Rules and Procedures (the “JAMS Rules”) then in effect (those rules are deemed to be incorporated by reference into this section, and as of the date of these Terms). The JAMS Rules and the JAMS Consumer Arbitration Minimum Standards, the latter effective July 15, 2009, are available at https://www.jamsadr.com.</p>
            <p>Arbitration will be handled by a sole, neutral arbitrator in accordance with the JAMS Rules. Judgment on the arbitration award may be entered in any court that has jurisdiction. Any arbitration under these Terms will take place on an individual basis – class, consolidated or representative arbitrations and class, consolidated or representative actions are not permitted. You understand that by agreeing to these Terms, you and the Company are each waiving the right to trial by jury or to participate in a class, consolidated or representative action or class, consolidated or representative arbitration. Court review of an arbitration award is limited. The arbitrator, however, can award on an individual basis the same damages and relief as a court (including injunctive and declaratory relief, or statutory damages). Notwithstanding the foregoing, you and the Company will have the right to bring an action in a court of proper jurisdiction for injunctive or other equitable or conservatory relief, pending a final decision by the arbitrator. You may instead assert your claim in “small claims” court, but only if your claim qualifies, your claim remains in such court and your claim remains on an individual, non-representative and non-class basis.</p>
            <p>The place of arbitration will be Ann Arbor, Michigan, but if you prefer a hearing in or closer to your hometown area, you and the Company will confer in good faith in order to identify a reasonable alternative location.</p>
            <p>Each of the Parties shall cooperate in good faith in the discovery or exchange of nonprivileged information relevant to the dispute as necessary in accordance with the JAMS Rules.</p>
            <p>The arbitrator’s award will consist of a written statement stating the disposition of each claim, and the award will also provide a concise written statement of the essential findings and conclusions on which the award is based.</p>
            <p>You and the Company shall maintain the confidential nature of the arbitration proceeding and the award, including the hearing, except as may be necessary to prepare for or conduct the arbitration hearing on the merits, or except as may be necessary in connection with a court application for a preliminary remedy, a judicial challenge to an award or its enforcement or unless otherwise required by law or judicial decision.</p>
            <h3>8.3 Costs of Arbitration</h3>
            <p>Payment for any and all reasonable JAMS filing, administrative and arbitrator fees will be in accordance with the JAMS Rules and the JAMS Consumer Arbitration Minimum Standards. If the value of your claim does not exceed $10,000, the Company will pay for the reasonable filing, administrative and arbitrator fees associated with the arbitration, unless the arbitrator finds that either the substance of your claim or the relief sought was frivolous or brought for an improper purpose. </p>
            <h3>8.4 Opt Out</h3>
            <p>You have the right to opt-out and not be bound by the arbitration provisions set forth in these Terms by sending written notice of your decision to opt-out to hello@candoor.io or to the mailing address listed in the “How to Contact Us” section of these Terms. The notice must be sent to the Company within thirty (30) days of your purchase of  the Offerings or agreeing to these Terms, otherwise you shall be bound to arbitrate disputes in accordance with these Terms. If you opt-out of these arbitration provisions, the Company also will not be bound by them. </p>
            <h2>9. Additional Provisions</h2>
            <h3>9.1 Updating These Terms</h3>
            <p>We may modify these Terms from time to time in which case we will update the “Last Revised” date at the top of these Terms.  If we make changes that are material, we will use reasonable efforts to attempt to notify you, such as by e-mail and/or by placing a prominent notice on the first page of the Website. However, it is your sole responsibility to review these Terms from time to time to view any such changes.  The updated Terms will be effective as of the time of posting, or such later date as may be specified in the updated Terms. Your continued access or use of the Services after the modifications have become effective will be deemed your acceptance of the modified Terms.  </p>
            <h3>9.2 Termination of License and Your Account</h3>
            <p>If you breach any of the provisions of these Terms, all licenses granted by the Company will terminate automatically. Additionally, the Company may suspend, disable, or delete your Account and/or the Services (or any part of the foregoing) with or without notice, for any or no reason. If the Company deletes your Account for any suspected breach of these Terms by you, you are prohibited from re-registering for the Services under a different name. In the event of Account deletion for any reason, the Company may, but is not obligated to, delete any of Your Content. The Company shall not be responsible for the failure to delete or deletion of Your Content. All sections which by their nature should survive the termination of these Terms shall continue in full force and effect subsequent to and notwithstanding any termination of these Terms by the Company or you. Termination will not limit any of the Company’s other rights or remedies at law or in equity. </p>
            <h3>9.3 Injunctive Relief</h3>
            <p>You agree that a breach of these Terms will cause irreparable injury to the Company for which monetary damages would not be an adequate remedy and the Company shall be entitled to equitable relief in addition to any remedies it may have hereunder or at law without a bond, other security or proof of damages.</p>
            <h3>9.4 California Residents</h3>
            <p>If you are a California resident, in accordance with Cal. Civ. Code § 1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting them in writing at 1625 North Market Blvd., Suite N 112 Sacramento, CA 95834, or by telephone at (800) 952-5210.</p>
            <h3>9.5 Miscellaneous</h3>
            <p>If any provision of these Terms shall be unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions. These Terms and the licenses granted hereunder may be assigned by the Company but may not be assigned by you without the prior express written consent of the Company. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. The section headings used herein are for reference only and shall not be read to have any legal effect. The Services are operated by us in the United States. Those who choose to access the Services from locations outside the United States do so at their own initiative and are responsible for compliance with applicable local laws. These Terms are governed by the laws of the State of Michigan, without regard to conflict of laws rules, and the proper venue for any disputes arising out of or relating to any of the same will be the arbitration venue set forth in Section 9, or if arbitration does not apply, then the state and federal courts located in Ann Arbor, Michigan.</p>
            <h3>9.6 How to Contact Us</h3>
            <p>You may contact us regarding the Services or these Terms at: 5701 Whispering Springs Drive, Ann Arbor, MI 48108 or by e-mail at hello@candoor.io.</p>



         </div>
        </div>
      </div>
    </div>
  </div>
</section>
<MainFooter />
</div>

        );
    }
}

export default termOfUse;
